const UserSignUpValidationNames = {

  SIGN_UP:"Sign Up",
  USER_NAME:"User Name",
  FULL_NAME:"Full Name",
  PASSWORD:"Password",
  PASSWORD_REPEAT:"Password Repeat",
  LOGIN:"Login",

  USER_NAME_CAN_NOT_BE_NULL: "USER_NAME_CAN_NOT_BE_NULL",
  USERNAME_MUST_BE_AT_LEAST_3_CHARACTERS:"USERNAME_MUST_BE_AT_LEAST_3_CHARACTERS",
  USERNAME_MUST_BE_UP_TO_255_CHARACTERS:"USERNAME_MUST_BE_UP_TO_255_CHARACTERS",
  
  FULL_NAME_CAN_NOT_BE_NULL: "FULL_NAME_CAN_NOT_BE_NULL",
  FULL_NAME_MUST_BE_AT_LEAST_1_CHARACTERS:"FULL_NAME_MUST_BE_AT_LEAST_1_CHARACTERS",
  FULL_NAME_MUST_BE_AT_LEAST_255_CHARACTERS:"FULL_NAME_MUST_BE_AT_LEAST_255_CHARACTERS",
  
  PASSWORD_CAN_NOT_BE_NULL: "PASSWORD_CAN_NOT_BE_NULL",
  PASSWORD_MUST_BE_AT_LEAST_6_CHARACTERS:"PASSWORD_MUST_BE_AT_LEAST_6_CHARACTERS",
  PASSWORD_MUST_BE_UP_TO_32_CHARACTERS: "PASSWORD_MUST_BE_UP_TO_32_CHARACTERS",
  PASSWORD_PATTERN_MESSAGE: "PASSWORD_PATTERN_MESSAGE",
  PASSWORDS_DO_NOT_MATCH: "PASSWORDS_DO_NOT_MATCH",
  PASSWORD_AUTHORIZATION: "PASSWORD_AUTHORIZATION",
};
export default UserSignUpValidationNames;
